### ISSUE TITLE
Data source support

### ISSUE THREAD

**Issue by snycc15** [WeBankFinTech/Exchangis#106]
The old version is mainly mysql. Does the new version support oracle?
老版本主要是以mysql为主，新版本是否支持oracle？

**Comment by jefftlin** [comment]
At present, the latest version is 1.1.0, which supports four data sources: mysql, hive, MongoDB and elasticsearch.

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
