### ISSUE TITLE
linkis-datasource-client

### ISSUE THREAD

**Issue by foxxxx001** [WeBankFinTech/Exchangis#109]
Dependencies required by dev-1.0. Where is this package? It has not been found in Linkis project.
dev-1.0需要的依赖，这个包在哪里啊，Linkis项目中也未发现？

**Comment by 77954309** [comment]
> dev-1.0需要的依赖，这个包在哪里啊，Linkis项目中也未发现

linkis pr

**Comment by Dlimeng** [comment]
> 同问。 另外，现在项目有人在推进吗？

developing

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1. You can pay attention to it.
