### ISSUE TITLE
The index type cannot be selected when the task destination data source is ES.

### ISSUE THREAD

**Issue by jkl0898** [WeBankFinTech/Exchangis#11]
![image](https://user-images.githubusercontent.com/14175165/83247713-84203d00-a1d6-11ea-9c82-cfde93d8a607.png)

1.version:
wedatasphere-exchangis-0.5.0

2.phenomenon:
As shown in the screenshot
Unable to select the index type, and cannot proceed to the next step.

1. 版本：
wedatasphere-exchangis-0.5.0

2. 现象：
如截图所示
无法选择索引类型，无法进行下一步。

**Comment by jkl0898** [comment]
原因：
ES 创建时没有写mappings, 指定mappings 后可以。

**Comment by jefftlin** [comment]
This problem had been solved! The latest version is exchangis1.1.1. You can pay attention to it.
