### ISSUE TITLE
Executor failed to get heartbeat, and reported Cannot get IP address #114.

### ISSUE THREAD

**Issue by zhangyiwen999** [WeBankFinTech/Exchangis#114]
I encountered this problem when I changed the platform for deployment, and the error log failed to get the ip. I have no problem with ipconfig on centos, and I have a physical network card.
换了台机部署就遇到这个问题，错误日志报无法获取ip，我在centos机上ipconfig是没问题的，有一张物理网卡

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
