### ISSUE TITLE
Exchange is configured mysql->es task, then click execute, and the task has been queued.

### ISSUE THREAD

**Issue by jkl0898** [WeBankFinTech/Exchangis#12]
![image](https://user-images.githubusercontent.com/14175165/83374283-be1f5800-a3fd-11ea-96af-b10caf8d5473.png)

1. version:
exchangis-0.5.0.RELEASE
2. Phenomenon
After configuring mysql -> es tasks, and clicking Execute, all tasks are in the queue state, but not in the execution state.
Observe the logs of service, executor and gateway, and no obvious error log is found.

1.版本：
exchangis-0.5.0.RELEASE
2. 现象
配置好mysql -> es  任务，并点击执行后， 所有任务都处于排队状态，没有进入到执行状态。
观察service、 executor、gateway 日志，未发现明显错误日志

Gateway continuous printing:
gateway 持续打印：
![image](https://user-images.githubusercontent.com/14175165/83374520-70efb600-a3fe-11ea-881d-794d2478bae7.png)

Service continuous printing:
service 持续打印：
![image](https://user-images.githubusercontent.com/14175165/83374545-8369ef80-a3fe-11ea-89c8-6a1e85136c38.png)

Executor continuous printing:
executor 持续打印：
![image](https://user-images.githubusercontent.com/14175165/83374564-94b2fc00-a3fe-11ea-8943-24f650fa0d85.png)

**Comment by jkl0898** [comment]
经定位， 原因是执行节点绑定了错误的ip 地址所致。已反馈。

**Comment by XuXuebin** [comment]
> 经定位， 原因是执行节点绑定了错误的ip 地址所致。已反馈。

这个有解决方案么？

**Comment by jkl0898** [comment]
> > 经定位， 原因是执行节点绑定了错误的ip 地址所致。已反馈。
> 
> 这个有解决方案么？

你好， 这个问题是绑定了错误的IP所致。解决方案是修正为绑定正确的IP。 
此问题我和该项目的拥有者一起定位， 并已向他反馈。如果你也遇到了一样的问题，
可先查看日志，确认是否同属于一样的问题。如果还有问题，可咨询此项目的拥有者。

**Comment by liushengjie** [comment]
> > > 经定位， 原因是执行节点绑定了错误的ip 地址所致。已反馈。
> > 
> > 
> > 这个有解决方案么？
> 
> 你好， 这个问题是绑定了错误的IP所致。解决方案是修正为绑定正确的IP。
> 此问题我和该项目的拥有者一起定位， 并已向他反馈。如果你也遇到了一样的问题，
> 可先查看日志，确认是否同属于一样的问题。如果还有问题，可咨询此项目的拥有者。

请问如何绑定的IP？

**Comment by liushengjie** [comment]
@jkl0898 请问如何绑定的IP？我也遇到了此问题

**Comment by jkl0898** [comment]
> @jkl0898 请问如何绑定的IP？我也遇到了此问题

你好。需要检查你的环境中网路相关的IP 配置， 你可查询其源码逻辑，关于IP绑定的部分。
也可以通过远程调试的方式调试错误。

**Comment by fs3085** [comment]
@jkl0898 你好，请问这个具体需要修改哪些配置

**Comment by zczy999** [comment]
> > @jkl0898 请问如何绑定的IP？我也遇到了此问题
> 
> 你好。需要检查你的环境中网路相关的IP 配置， 你可查询其源码逻辑，关于IP绑定的部分。 也可以通过远程调试的方式调试错误。

大佬能不能详细的说明下，或者给个具体的类名，非常感谢

**Comment by jefftlin** [comment]
This problem had been solved! The latest version is exchangis1.1.1. You can pay attention to it.
