### ISSUE TITLE
Exchange is configured mysql->mysql task, then click execute, and the task has been queued.

### ISSUE THREAD

**Issue by zczy999** [WeBankFinTech/Exchangis#123]
![image](https://user-images.githubusercontent.com/23332089/142350164-836eb56f-5835-4193-ba66-05e30d1ad1b2.png)

1.版本：
exchangis-0.5.0.RELEASE
2. 现象
配置好mysql -> mysql 任务，并点击执行后， 所有任务都处于排队状态，没有进入到执行状态。
观察service、 executor、gateway 日志，未发现明显错误日志

1. version:
exchangis-0.5.0.RELEASE
2. phenomenon
After configuring mysql -> mysql tasks, and clicking Execute, all tasks are in the queue state, but not in the execution state.
Observe the logs of service, executor and gateway, and no obvious error log is found.

https://github.com/WeBankFinTech/Exchangis/issues/12
And I see that the previous issue has been solved. Can you explain in detail where to change it? Thank you.
并且我看到之前的issue已经解决了，能不能详细的说明下要改哪里，谢谢

**Comment by zczy999** [comment]
找到了ExecutorServiceImpl类中init()方法中
String host = MachineInfo.getIpAddress(configuration.getNetworkInterface());
调用getIpAddress方法时，如果机器中多个ip地址，比如虚拟机ip，就会产生ip绑定bug，导致executor服务不正常，然后在前端显示时一直在排队中。
建议直接有个ip配置项来修复这个bug

**Comment by zczy999** [comment]
还发现一个问题，Executor这个服务需要libsigar-amd64-linux.so lib文件，不然也会执行失败。这个通过脚本执行的时候不会报错，只有自己去java命令行启动时才会发现缺少类库，不懂什么情况

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了

**Comment by zhanghaicheng1** [comment]
根据指定ip获取网卡名称，脚本如下：
1、比如你需要绑定的executor的ip是10.0.0.14
2、获取网卡名称如下：

#!/bin/bash
ip="10.0.0.14"
interfaces=(`ip l | awk -F":"  '/^[^ ]/{print $2}'| awk '{print $1}'`)
for interface in ${interfaces[*]};do
     rs=`ip a show $interface| grep $ip`
     if [ -n "$rs"   ];then
         echo $interface                                                                                                                                                   
         break
     fi
done
3、将获取的网卡名字，比如第二步输出的结果是“em1”
4、将第3步骤的结果配置到/wedatasphere-exchangis-0.5.0.RELEASE/modules/exchangis-executor/conf/bootstrap.yml的

network:
    interface:
      name: "em1"
5、重启exchangis-executor、以及exchangis-service服务

./bin/start.sh -m exchangis-executor
./bin/start.sh -m exchangis-service
6、大功告成，附上一张测试成功的截图（hive同步mysql，一条数据）
<img width="1958" alt="image" src="https://user-images.githubusercontent.com/46189785/175271021-b1af849e-684a-451a-8edf-0b4e60092492.png">
