### ISSUE TITLE
After the installation, the simple mysql synchronization task has been waiting.

### ISSUE THREAD

**Issue by wytalw** [WeBankFinTech/Exchangis#124]
I have read the situation of others, saying that the ip of the execution node is inconsistent, and it has been adjusted manually, but it still can't perform the synchronization task. Is there a solution?
看过其他人的情况，说执行节点ip不一致，也手动调整了，还是无法执行同步任务，有没有解决办法？

**Comment by wytalw** [comment]
这个0.5版本的是不是不维护了？

**Comment by zczy999** [comment]
> 这个0.5版本的是不是不维护了？

我感觉是，去看海豚调度吧，比这个好太多了

**Comment by wushengyeyouya** [comment]
The community is currently integrating Exchangis into DSS, please keep tuned!

**Comment by wushengyeyouya** [comment]
Please give us some more detail error messages to solve this problem.

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
