### ISSUE TITLE
Error during compilation: dss-appjoint-auth-0.9.0.jar is missing.

### ISSUE THREAD

**Issue by wrhwww** [WeBankFinTech/Exchangis#125]
Missing DSS-appjoint-auth-0.9.0.jar while compiling exchangis-service.
编译exchangis-service时报缺少dss-appjoint-auth-0.9.0.jar

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了

**Comment by jefftlin** [comment]
The new version of dss has fixed this problem and updated the latest code.
