### ISSUE TITLE
Do Exchangis support automatic creation of destination tables when data is included?

### ISSUE THREAD

**Issue by LEOPROGRAM** [WeBankFinTech/Exchangis#128]
When creating access data, the destination table selection must specify the table name, and whether it is well enough to support the automatic creation of new tables. thank you
创建接入数据的时候，目的表选择必须指定表名，是否嗯能够够支持自动创建新表。谢谢

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了

**Comment by jefftlin** [comment]
No, tables must exist first.
