### ISSUE TITLE
Unable to find instance for EXCHANGIS-SERVICE

### ISSUE THREAD

**Issue by galesun** [WeBankFinTech/Exchangis#14]
Unable to find instance for Exchangis-Service after opening the WEB interface

**Comment by galesun** [comment]
The reason may be that my environment is using mysql-8.0+ and I cannot connect to the database

**Comment by Davidhua1996** [comment]
You can check if you have installed mysql command on your server.If not, try to init database manually according to the installation document.

**Comment by cuikai2015** [comment]
> The reason may be that my environment is using mysql-8.0+ and I cannot connect to the database

have same error, how to connet mysql 8.0+

**Comment by galesun** [comment]
Recompile and run with the MySQL8 driver to see the information below the error log prompt for the service
"Caused by: com.mysql.cj.exceptions.InvalidConnectionAttributeException: The server time zone value 'EDT' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support."
**My solution:**
1.In..This problem is resolved by finding the location of the application.yml configuration and adding serverTimezone=UTC, as follows
Url: JDBC: mysql: / / ${DB_HOST: 127.0.0.1} : ${3306} DB_PORT: / ${DB_DATABASE: exchangis}?UseUnicode = true&characterEncoding = utf-8 & serverTimezone = UTC
2.Install the MySQL5 database

**Comment by jefftlin** [comment]
Please check whether there is a problem with the startup procedure. The latest version is exchangis1.1.1. You can pay attention to it.
