### ISSUE TITLE
[Open source] Exchangis1.0 error in deleting project.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#197]
Deleting a project will throw an exception stack and cannot be deleted. It should be optimized so that a pop-up box prompts that the project has a task.
删除项目会抛出异常栈，并且无法删除，应优化为出现弹框提示该项目存在任务
![image](https://user-images.githubusercontent.com/27387830/156139024-997450bc-c18f-4798-839f-753ed23d28b4.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
