### ISSUE TITLE
[Open source] Exchangis1.0 task configuration optimization.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#199]
Task configuration adding parameters can be saved even if they are blank; The word "Add Variable" is not a click button, but variable parameters can still be added, and it should be optimized as an obvious click form. Delete flag is offset from parameter variable.
任务配置添加参数即使为空，也能够进行保存；《添加变量》四个字不是点击按钮，但依旧可添加变量参数，应优化为明显的点击形式。删除标志与参数变量有偏移
![image](https://user-images.githubusercontent.com/27387830/156139813-bc3df986-b715-4a90-875d-6b0dc0678b1c.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
