### ISSUE TITLE
[Open source] Exchangis1.0 task configuration variable submits null value.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#200]
For empty variable parameters, it is still added to JobParams.
对于空的变量参数，依旧往JobParams里面添加了
![image](https://user-images.githubusercontent.com/27387830/156140211-652b185d-49ff-4cd7-a0fb-e0a2ba52a2ff.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
