### ISSUE TITLE
[Open source] Exchangis1.0 sidebar collection and display problem.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#203]
After collecting the sidebar, only the general collection should be optimized to complete collection.
对侧边栏进行收取操作后，只收取了一般，应优化为完全收取
![image](https://user-images.githubusercontent.com/27387830/156140879-2a15b3bf-93c2-4be4-8f8d-0a38ec25a9a0.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
