### ISSUE TITLE
[Open source] Exchangis1.0 data source search problem.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#207]
The searched library can be displayed, but click on the library to expand the table. Although the interface correctly returns the table, it is not displayed on the interface.
搜索出的库能显示，但是点击库展开表，虽然接口正确返回了表，但是没有在界面上显示
![image](https://user-images.githubusercontent.com/27387830/156142001-616dac2f-57f5-4957-b30f-995497527faf.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
