### ISSUE TITLE
[Open source] Exchangis1.0 task pulling progress problem.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#208]
After clicking Execute Task, even if you exit the task interface, you will keep asking the backend for progress information.
点击执行任务后，即使退出任务界面，也会不停的向后端请求进度信息
![image](https://user-images.githubusercontent.com/27387830/156142222-4e5d5135-3314-4f7f-b0be-6fc444ef3856.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
