### ISSUE TITLE
[Open source] Exchangis1.0 field mapping is not refreshed.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#209]
After changing the library table of the data source, the field mapping has not changed dynamically, and the back-end has returned the new field mapping value normally.
更换数据源的库表之后，字段映射并没有相应的动态改动，此时后端已经正常返回了新的字段映射值
![image](https://user-images.githubusercontent.com/27387830/156142399-4854d736-03c2-47c5-98ee-9d43f60b89d9.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
