### ISSUE TITLE
[Open source] Exchangis1.0 fails to perform the task, but still pulls the progress.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#211]
When the task status is failed, it still keeps pulling the progress to the background.
当任务状态为失败时候，依旧在不停的向后台拉取进度
![image](https://user-images.githubusercontent.com/27387830/156142807-bfd13d30-a8a4-49dd-baae-d1b34bade7d4.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
