### ISSUE TITLE
[Open source] Error in editing Exchangis1.0 data source.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#212]
After the data source is edited and saved, an error will be reported that the comment parameter cannot be empty, that is, the comment in the uploaded parameter is empty, resulting in the editing and saving failure.
数据源编辑保存之后，会报comment参数不能为空的错误，也就是上传的参数中comment为空，导致编辑保存失败
![image](https://user-images.githubusercontent.com/27387830/156143027-8746f8d8-9847-4951-ab0e-f8b5ea7a19a3.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
