### ISSUE TITLE
[Open source] Optimization of Exchangis1.0 Front-end Cache Log Rows.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#213]
It is recommended that the front-end cache log should be set to 1000-2000 lines at the maximum, and the previous ones will be discarded if it exceeds the limit.It is recommended that the front-end cache log should be set to 1000-2000 lines at the maximum, and the previous ones will be discarded if it exceeds the limit.
建议前端缓存日志最大设置为1000-2000行，超过的则丢弃之前的

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
