### ISSUE TITLE
[Open source] Optimization of Exchangis1.0 Pull Log Timer.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#214]
When the log switches task/job in real time, the first pull will be triggered immediately (that is, there will be no delay in the first pull, and it will be displayed immediately after it is pulled, and there will be a time interval after the second pull.
实时日志切换task/job的时候，即时触发第一次拉取（就是第一次拉取的时候没有延时，拉到了马上显示，第二次开始才有时间间隔

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
