### ISSUE TITLE
[Open source] Optimization of Exchangis1.0 project name length.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#215]
It is suggested that the length of project name and task name should not exceed one hundred.
建议项目名称和任务名称长度不能超过一百
![image](https://user-images.githubusercontent.com/27387830/156143628-eef967b1-c513-4db6-a682-46c528953191.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
