### ISSUE TITLE
[Open source] Exchangis1.0 project card name boundary display problem.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#216]
If the name of an item is too long, the display will exceed the boundary, and the extra-long part can be represented by < ... >.
 项目名称太长时显示会超出边界，超长的部分可用<....>表示
![image](https://user-images.githubusercontent.com/27387830/156143856-fbc496a8-3b67-4c8f-9203-a97bed997bf5.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
