### ISSUE TITLE
[Open source] Issue that error prompt when Exchangis1.0 task execution log is empty.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#219]
error prompt when Exchangis1.0 task execution log is empty. 
日志为空时报错
![image](https://user-images.githubusercontent.com/27387830/156146488-0199decd-df5d-40e4-8540-8fe4c774ff9a.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
