### ISSUE TITLE
[Open source] The log pull did not stop after Exchangis1.0 kill operation.

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#220]
After the kill is terminated, the log is still being pulled. If the kill is successful, make sure to stop the log pulling. Now the problem is:
Kill or close the console without closing the scheduled task of pulling logs (if kill fails, the console does not need to be closed, and logs are pulled normally).
There is a situation now, if I click Run Log, select the log of a task, and then kill the task, although it shows that the kill is successful, the log is still being pulled.
Now close the console and kill the task at the same time.
kill终止后，日志还在拉，kill成功了一定要确保停止日志拉取，现在的问题：
Kill或者关闭控制台，没有关闭拉日志的定时任务(如果kill失败，控制台不用关闭，正常拉日志）。
现在存在的一种情况是，如果我点击运行日志，选择一个task的日志后，再kill掉任务，虽然显示kill成功，但是日志依旧在拉。
同时现在关闭控制台，要同时kill掉任务
![image](https://user-images.githubusercontent.com/27387830/156146813-dfe2aea1-cae7-46b5-8b3e-a0a4c0a21457.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
