### ISSUE TITLE
[Open source] Issue that Exchangis1.0 task execution module-task stop status display.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#234]
There seems to be something wrong with the front-end judgment logic. allTaskStatus returned by the last pulled status interface is true, indicating that all the current tasks have reached the final state. The status of the job is Scheduled at this time, so the page refresh is stopped, and the execute button remains in the stopped state.
前端判断逻辑似乎有问题，最后一个拉取的status接口返回的allTaskStatus是true，表示当前所有任务已经到终态，job的status此时是Scheduled，就停止了页面刷新，并且执行按钮一直保持在停止状态。
![_U8oL4EV4LyO5f-jT8C3jw](https://user-images.githubusercontent.com/30531485/158964050-21ed470a-73ef-490f-8b1d-7fa2761513fe.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
