### ISSUE TITLE
[Open source] Issue that Exchangis1.0 task configuration adding parameter is blank, and it can be saved.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#235]
Task configuration adding parameters can be saved even if they are blank; The word "Add Variable" is not a click button, but variable parameters can still be added, and it should be optimized as an obvious click form. The deletion flag is offset from the parameter variable, and the lower position is optimized.Task configuration adding parameters can be saved even if they are blank; The word "Add Variable" is not a click button, but variable parameters can still be added, and it should be optimized as an obvious click form. The deletion flag is offset from the parameter variable, and the lower position is optimized.
任务配置添加参数即使为空，也能够进行保存；《添加变量》四个字不是点击按钮，但依旧可添加变量参数，应优化为明显的点击形式。删除标志与参数变量有偏移，优化下位置
![bc_CSX1ml9y9Xv7zg0xPaw](https://user-images.githubusercontent.com/30531485/158947575-f6f800c7-7198-4649-8a03-918b9198b9aa.png)

For empty variable parameters, it is still added to JobParams.
对于空的变量参数，依旧往JobParams里面添加了
![k-zLpWsQC03jkdzH6jaPYg](https://user-images.githubusercontent.com/30531485/158947900-b058ed89-ecf8-4693-80e3-5a4a8a99b8dc.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
