### ISSUE TITLE
[Open source] Issue that Exchangis1.0 data source management-version display sorting.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#236]
The list of versions should be displayed in reverse order, with the latest one at the top, so that users can choose.
版本列表应为倒序显示，最新的在最上面，以便用户选择

![jquX-Jf282OAIj0Ltd1G1Q](https://user-images.githubusercontent.com/30531485/158948384-e5f0cb6c-8ca5-4c4c-84c8-6dba07290ff3.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
