### ISSUE TITLE
[Open source] Issue that Exchangis1.0 new and modified project project name verification.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#237]
The entered project name has not been format-checked as prompted, and can still be saved.
输入的项目名没有按照提示的那样进行格式校验，依旧能保存
![vg7I4EPOurSkrinx0JOhkQ](https://user-images.githubusercontent.com/30531485/158948853-af494210-0f8b-4375-9679-b15e2b872c67.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
