### ISSUE TITLE
[Open source] Issue that Exchangis1.0 subtask list-select data source for caton optimization.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#238]
When selecting a library table, you need to have a search box, otherwise it will be difficult to find the desired library table if there are too many library tables; At the same time, if too much information in the loading library table leads to slow response, it is necessary to add a covered loading box, otherwise the loading will get stuck.
 选择库表的时候，需要有一个搜索框，不然库表太多很难找到想要的库表；同时，加载库表信息如果太多导致响应慢的话，还是要加个遮盖的加载框，不然加载会卡
![1mW_E-L_kDl5mX0a-McG7Q](https://user-images.githubusercontent.com/30531485/158949624-b1cb87dc-14a7-44aa-9db9-5270d80c41b0.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
