### ISSUE TITLE
Is dockerfile supported?

### ISSUE THREAD

**Issue by duyong6380** [WeBankFinTech/Exchangis#24]
I mean, not all modules are in one dockerfile, but different modules are in different dockers.
我的意思不是所有的模块都放在一个dockerfile中，而是不同模块在不同的docker中

**Comment by Davidhua1996** [comment]
You can use the single module in docker by setting port mappings

**Comment by jefftlin** [comment]
This function is not planned to be implemented in the current version. The latest version is exchangis1.1.1. You can pay attention to it.
