### ISSUE TITLE
[Open source] Issue that Exchangis1.0 query log is displayed incorrectly.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#240]
After clicking the query, this log is wrong, and it becomes the log of job. It should be the log of the task hello.
点击查询后这个日志不对，变成了job的日志，应该是hello这个task的日志
![H2FdKmvDzW9DKghGYQGgPw](https://user-images.githubusercontent.com/30531485/158953410-dfe70575-7b0e-4100-9fd2-ff205739f744.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
