### ISSUE TITLE
[Open source] Issue that Exchangis1.0 subtask log is missing.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#241]
Search before asking

- [x] I had searched in the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar feature requirement.

Problem Description
Exchangis1.0 subtask log is missing. 

Description
Exchangis1.0 subtask log is missing. 
![MkNOvk81ocZJiM4zkbHw3g](https://user-images.githubusercontent.com/30531485/158953638-f3af662b-8bea-4be0-89f8-131d0f81f62d.png)
![4mOM-_Uoa7PciCEd2DV0cg](https://user-images.githubusercontent.com/30531485/158953644-67787851-e1b0-4a45-ba60-d45de74764c3.png)

Use case
No response

solutions
No response

Anything else
No response

- [x] Are you willing to submit a PR?

Yes I am willing to submit a PR!

**Comment by FinalTarget** [comment]
#282 The bug has been resolved
