### ISSUE TITLE
【开源】Exchangis1.0 数据源选择无限加载问题

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#242]
来回选择数据源时，会出现无限加载的情况
![pdSlW7UDaaVlllIlmZZQRQ](https://user-images.githubusercontent.com/30531485/158953880-762fa925-f610-404e-b2a3-67f988047972.png)

**Comment by jefftlin** [comment]
> 来回选择数据源时，会出现无限加载的情况 ![pdSlW7UDaaVlllIlmZZQRQ](https://user-images.githubusercontent.com/30531485/158953880-762fa925-f610-404e-b2a3-67f988047972.png)
