### ISSUE TITLE
[Open source] Issue that modify promot when Exchangis1.0 pull log/progress timeout.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#243]
For the time-out of logging/progress retrieval, change it to a reminder as the case may be, instead of printing the words "system error" 
对于拉取日志/进度超时，看情况改成提醒，而不是打印"系统错误"字样
![MYkur50tNk9lmsx8KsteBQ](https://user-images.githubusercontent.com/30531485/158954108-9fddbf4b-9bcd-49cb-add0-77dd15314730.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
