### ISSUE TITLE
[Open source] Issue that exchangis1.0 execution node has no normal display.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#244]
The execution node is not displayed normally. It may be that the field name of the front end does not correspond to the passed jobExecutionId. Originally, the front end should be jobId, but now it is obtained by jobExecutionId. 
执行节点没有正常显示，可能是前端的字段名与传递来的jobExecutionId不对应，原来前端应该是jobId，现在改为了jobExecutionId获取
![92rhSRYJ6aZ3sIfiNa5mYw](https://user-images.githubusercontent.com/30531485/158954450-0b8516b9-e816-4441-8025-f39d947d1f2f.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
