### ISSUE TITLE
[Open source] Exchangis1.0 modifies the status conditions in the supplementary synchronization history.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#245]
'Inited': '准备',
        'Scheduled': '预排',
        'Running': '运行中',
        'WaitForRetry': '等待重试',
        'Cancelled': '取消',
        'Failed': '失败',
        'Partial_Success': '部分成功',
        'Success': '运行成功',
        'Undefined': '未定义',
        'Timeout': '超时'
![LuspeyvKnFK1LPO8Qk3AEA](https://user-images.githubusercontent.com/30531485/158954712-e4a3b510-44af-4f05-85bc-02276ad61f73.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
