### ISSUE TITLE
[Open source] Exchangis1.0 adds an interface for deleting synchronization history.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#248]
Delete records in synchronization history
Description: jobExecutionId, delete synchronization history
The request URL:/api/rest_j/v1/exchangis/job/{jobExecutionId}/deleteJob
Request method: POST
删除同步历史中的记录
接口描述：jobExecutionId，删除同步历史记录
请求URL：/api/rest_j/v1/exchangis/job/{jobExecutionId}/deleteJob
请求方式：POST

{
"method": "/api/rest_j/v1/exchangis/job/{jobExecutionId}/deleteJob",
"status": 0,
"message": "Submitted succeed(提交成功)！",
"data": {
"jobExecutionId": "555node1node2node3execId1"
}
}
![XbuhAEnmrSy-JQPGjPG5KQ](https://user-images.githubusercontent.com/30531485/158955531-82c2918d-a353-4cdf-9bcb-1bda0817d3b6.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
