### ISSUE TITLE
[Open source] Modify the copy of the Exchangis1.0's log prompt.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#249]
"Already on the last page" is changed to "End of query log"
“已经在最后一页"改为“查询日志结束
![1YpTXSMrwYV7Tueb-MvCtw](https://user-images.githubusercontent.com/30531485/158955931-670fdeae-2960-477e-a155-222fc92a87e9.png)
”

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
