### ISSUE TITLE
I need to support oracle and sqlserver. I can't add a supporting data source. I want to handle it.

### ISSUE THREAD

**Issue by duyong6380** [WeBankFinTech/Exchangis#25]

**Comment by Davidhua1996** [comment]
Because that we don't use oracle internally, exchangis doesn't support oracle/sqlserver in the current version.We will solve in the next version

**Comment by duyong6380** [comment]
大概什么时候能够出来下个版本

**Comment by duyong6380** [comment]
就是前端不限制，后端才好定制啊，要不然我们根本无法使用这个框架，因为有很多数据库无法支持。

**Comment by duyong6380** [comment]
有没有邮箱或者是微信，能直接交流吗？

**Comment by Davidhua1996** [comment]
We will release the front code in August. For more questions, you can consult WeChat: **david_hua1996**

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1 and had supported Oracle. You can pay attention to it.
