### ISSUE TITLE
[Open source] Issue that system error prompt when exchangis1.0 reads the last n lines and inputs decimals.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#250]
![bvH7KF2v8rWQRxg-eyTVqQ](https://user-images.githubusercontent.com/30531485/158956858-b0861069-b79a-4d59-a5ce-0ab10d51993a.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
