### ISSUE TITLE
[Open source] Issue that error prompt when exchangis1.0 enter the name of the existing project.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#251]
Front-end: system exception
前端提示：系统异常

Error in background: message: "Failed to create the project because of: errcode: 30041, desc: exchange is. project.create.error.name.exists, IP: bdpudes10002, port: 9321, servicekind: exchange is-server"
后台报错：message: "创建工程失败,原因是:errCode: 30041 ,desc: exchangis.project.create.error.name.exists ,ip: bdpudes100002 ,port: 9321 ,serviceKind: exchangis-server"

Front-end prompt: "System Exception" is changed to "Project with the same name already exists"
前端提示：《系统异常》改为《已存在同名项目》

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
