### ISSUE TITLE
[Open source] Issue that error prompt when Exchangis1.0 modifies the description and label of data source.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#252]
Modifying the description and label of the data source is a super-long string, and an error will be reported. Parameters need to be verified, and the field length is limited to 254.
修改数据源的描述和标签为超长字符串，会报错误，需校验参数，限制字段长度在254以内
![XAEiXRiA6MnggtMDMGJTyg](https://user-images.githubusercontent.com/30531485/158957937-17c1283b-e735-426c-9faf-c68e361640f6.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
