### ISSUE TITLE
[Open Source] Issue that error prompt when exchangis1.0 data source's display of super-long character labels

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#253]
The data source does not display the super-long character label well, the super-long string label needs to be changed to XXXX. ..
数据源展示对于超长的字符标签，没有做好显示，对于超长字符串标签，需改为XXXX..

![g11JSReJ7bn-zp_vdk_4WA](https://user-images.githubusercontent.com/30531485/158958235-f9200a8a-a3a8-40c1-8df7-94f9b5f850dc.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
