### ISSUE TITLE
[Open source] Issue that error prompt when Exchangis1.0 data source is unpublished

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#254]
If the data source is not published, the creation task will report an error when referencing the data source, optimize the exception prompt, and only display "The data source is not published or the parameter is empty".
数据源未发布，创建任务引用该数据源报错，优化该异常提示，只显示《数据源未发布或参数为空》

![N_rub1BcoE4EihnttEWlgQ](https://user-images.githubusercontent.com/30531485/158962304-2b838781-2eb2-48e6-8ab5-db72ce434310.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
