### ISSUE TITLE
 [Open source] Exchangis1.0 deleting the referenced data source will prompt an abnormal problem.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#255]
Delete the referenced data source, report an error exception, and optimize the exception with the prompt "There is reference dependency at present, so it cannot be deleted"
删除被引用的数据源，报错误异常，优化该异常提示为《目前存在引用依赖，不可删除》
![9AiG8O210dDrmM3sELr1xg](https://user-images.githubusercontent.com/30531485/158962614-a1ef5266-ea63-4310-8364-54ada917f2f7.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
