### ISSUE TITLE
[Open source] Exchangis1.0 create a data source, and when the entered name already exists, there is an exception, prompting optimization.

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#257]
Create a data source, the entered name already exists, and an exception will be reported. The error prompt for optimization is "A data source with the same name already exists"
创建数据源，输入的名称已存在会报异常，优化该错误提示为《已存在同名数据源》
![rZZAj1_jp-t7PB4GjAGI4g](https://user-images.githubusercontent.com/30531485/158963274-2947619a-0802-4059-b12d-33c2c16e77b0.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
