### ISSUE TITLE
[Open source] Log display problems in the synchronization history of Exchangis1.0

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#258]
The logs in the history of synchronization, just click in and there is no log refresh. You have to select other subtasks first, and then click back to job to have the log refresh.
同步历史中的日志，刚点进去没有日志刷新，要先选择别的子任务，再点回job才有日志刷新
![cv_ATJh1_DwejqK_Cr_7gw](https://user-images.githubusercontent.com/30531485/158964431-062cb9c1-fd33-4d8a-995c-5c1fc6cc57cd.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
