### ISSUE TITLE
[Open source] Exchangis1.0 synchronization history list data display problem

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#259]
When the query result is empty, it should also be displayed as empty instead of caching the data before the query:
查询结果为空时，也应该展示为空，而不是缓存查询之前的数据：
![-LbYj34qRgSPBF0IPRzslQ](https://user-images.githubusercontent.com/30531485/158965282-85857e51-c327-4a4a-ac92-cc439387cc7c.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
