### ISSUE TITLE
Sqoop performs tasks.

### ISSUE THREAD

**Issue by Dlimeng** [WeBankFinTech/Exchangis#26]
Execute the task with sqoop engine and report an error:
java.lang.IllegalArgumentException: Cannot find the SQOOP Tool option: ["{}"]
用sqoop引擎执行任务，报错：
java.lang.IllegalArgumentException: Cannot find the SQOOP Tool option: ["{}"]

**Comment by Davidhua1996** [comment]
You can view the commit "Adjust sqoop template configuration"

**Comment by 77954309** [comment]
> You can view the commit "Adjust sqoop template configuration"

谢谢。已经解决了
