### ISSUE TITLE
[Open Source] Problem with progress bar display when Exchangis1.0 job fails

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#260]
When the job fails, the progress bar is displayed in red
job失败时，进度条展示为红色

![HFeIJTKiGC5oCVIgY8u4ZQ](https://user-images.githubusercontent.com/30531485/158965647-965b033d-73d8-4445-839c-c6ab011f9cd1.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
