### ISSUE TITLE
[Open source] Exchangis1.0 synchronization historical data display problem

### ISSUE THREAD

**Issue by one-beauty** [WeBankFinTech/Exchangis#261]
Synchronize the history, click the execution ID 1, and the operation status pop-up box will pop up; click the execution ID 2 again, the data returned in the background is correct, and the front end is still the running status of ID 1, unless the pop-up box is closed and the data is reopened.
同步历史，点击执行ID 1，弹出运行情况弹框；再次点击执行ID 2，后台返回数据正确，前端依旧是ID 1的运行情况，除非关闭弹框重新打开数据才正确
![GCKrJquWjjohayZTcNM6Sw](https://user-images.githubusercontent.com/30531485/158967265-406da047-f3fb-4c8f-890d-4b59fbfda319.png)

**Comment by jefftlin** [comment]
https://github.com/WeBankFinTech/Exchangis/pull/282，这个pr解决了
