### ISSUE TITLE
When building Exchangis data exchange development environment, dss-appjoint-auth:0.9.0 dependency package is missing.

### ISSUE THREAD

**Issue by zslali** [WeBankFinTech/Exchangis#267]
Which guys has this dependency package, so it's convenient to share it?
在搭建exchangis数据交换开发环境时，缺少dss-appjoint-auth:0.9.0依赖包，哪位大佬有这个依赖包，方便给分享一下？

**Comment by jefftlin** [comment]
The new version of dss has fixed this problem and updated the latest code.
