### ISSUE TITLE
Local debug data exchange project exchangis

### ISSUE THREAD

**Issue by zslali** [WeBankFinTech/Exchangis#268]
Guys, how do you debug data exchange project exchangis locally?
各位大佬，如何在本地debug数据交换exchangis呢？

**Comment by jefftlin** [comment]
1、Set DEBUG_MODE=False and DEBUG_PORT="7006" in sbin/launcher.sh
2、Start exchangis server with command "./daemon start server" in sbin/daemon.sh
Then you can see the printing log with "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=${DEBUG_PORT}"
On the premise of this, you need to start dss(https://github.com/WeBankFinTech/DataSphereStudio) and linkis(https://github.com/apache/incubator-linkis)
