### ISSUE TITLE
Exchange is unable to heartbeat, the execution task has been queued, and the node cannot be displayed.

### ISSUE THREAD

**Issue by M970203** [WeBankFinTech/Exchangis#285]
Exchange is always waiting in line when performing tasks. The log shows heartbeat problem, and the node cannot be obtained. After modification according to the installation steps, there is no result.
Exchangis执行任务的时候一直在排队，日志显示心跳问题，无法获取节点，按照安装步骤修改后，无果
![图片](https://user-images.githubusercontent.com/104344397/170459511-65b8bef6-1ca8-47a9-a30e-7fdc71f89026.png)
![图片](https://user-images.githubusercontent.com/104344397/170459606-1e02dea6-83d0-4665-a4f0-fe4798a57649.png)
![图片](https://user-images.githubusercontent.com/104344397/170459688-ff828498-b5cf-40d3-8b0d-478b86f4b97f.png)
After several versions of the virtual machine test environment, the problem is still the same. At first, the ip of the node in the setting interface does not come out directly or is the wrong ip. After solving according to the scheme, the ip in the setting is normal, but the task node is still not obtained. Ask for the solution.
换了几个版本的虚拟机测试环境还是一样的问题。刚开始设置界面里的节点ip直接不出来或者是错误ip，根据方案解决后设置里面ip正常了，但是任务节点还是不获取，请教解决方法

**Comment by M970203** [comment]
时区也统一成了GTM，

**Comment by jefftlin** [comment]
This problem had been solved! The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
