### ISSUE TITLE
[Enhennce] Dev 1.0.0-rc update linkis version to 1.1.0 to 1.1.1

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#297]
### Search before asking

- [x] I searched the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar issues.

### What happened + What you expected to happen

The Linkis 1.1.0 version does not adapt to the Exchangis1.0-rc version, and the deployment documentation needs to be optimized

### Relevent platform
all

### Reproduction script
no

### Anything else
No response

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by jefftlin** [comment]
Done
