### ISSUE TITLE
Implement SSO(single sign-on) with DSS

### ISSUE THREAD

**Issue by Adamyuanyuan** [WeBankFinTech/Exchangis#32]
We need implement SSO  with DSS, to facilitate users to jump from DSS to Exchangis

**Comment by schumiyi** [comment]
Notes:  
The following steps are required so that sso from DSS to Exchangis can work well:
0. The environment of Exchangis: 
    a. Exchangis-0.5.0
    b. DSS-0.9.0: Sso is dependent on dss-appjoint-auth-0.9.0.jar by default, which is based on DSS-0.9.0
    c. Linkis-0.9.4: dss-0.9.0 is based on Linkis-0.9.4
1. Add the following config to /modules/exchangis-service/conf/auth.properties
```
auth.redirect.url=/api/v1/auth/redirect
```
2. Execute the following DML in database of DSS:
```
update dss_application set redirect_url='http://ip:port/api/v1/auth/redirect' where name='exchangis';
```

**Comment by jefftlin** [comment]
It had been solved! The latest version is exchangis1.1.1. You can pay attention to it.
