### ISSUE TITLE
[Enhance] Front end display optimization point

### ISSUE THREAD

**Issue by jefftlin** [WeBankFinTech/Exchangis#346]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar feature requirement.

### Problem Description

Some frontend optimization points

### Description

1、Project name highlighting optimization
![image](https://user-images.githubusercontent.com/57786627/187636740-4a7c2998-2b11-4137-9b19-050fc54f818e.png)
2、Highlight and optimize the menu bar
![企业微信截图_16615208882383](https://user-images.githubusercontent.com/57786627/186915705-060e0dcb-0092-4ef8-8154-5b567ffdb54b.png)
3、Parameter configuration pop-up window optimization
![企业微信截图_16615209098546](https://user-images.githubusercontent.com/57786627/186915802-2c941535-1b9d-44be-8c10-f67b3af4eb67.png)
4、Browser adaptation interface optimization
![企业微信截图_16615209231896](https://user-images.githubusercontent.com/57786627/186915841-fbb4b869-242c-4869-a773-c42dab652afc.png)
5、Partition information input box optimization
![企业微信截图_16615209361506](https://user-images.githubusercontent.com/57786627/186915875-337bf100-27d4-4a21-b60c-aca78c689be7.png)
![企业微信截图_16615209464248](https://user-images.githubusercontent.com/57786627/186915929-c9654795-08d3-464f-9cd6-17e73e9569b9.png)
6、Paging support for field mapping
![企业微信截图_16615209626538](https://user-images.githubusercontent.com/57786627/186915971-09c01f4b-41f1-43b9-acfa-ab8dff03cda7.png)
![企业微信截图_1661520969309](https://user-images.githubusercontent.com/57786627/186915999-1a90fe37-f801-4a82-9ac5-a1566ac70b9f.png)
7、Configure data source echo support
![企业微信截图_16615209794457](https://user-images.githubusercontent.com/57786627/186916033-63bbe269-3971-4be3-8971-9e5122018c57.png)
8、Optimization of interface scaling dislocation
![企业微信截图_16615209888867](https://user-images.githubusercontent.com/57786627/186916065-27691d9a-7fff-423c-aaf4-b79252b7150f.png)
9、Add default name for copy subtask
![企业微信截图_16615210091046](https://user-images.githubusercontent.com/57786627/186916144-f9a2e4c4-b89b-4189-b6d3-897872b6e5bb.png)
10、Configure data source interface optimization
![image](https://user-images.githubusercontent.com/57786627/186916226-954da8f9-a604-4aa6-b6f4-1674a1f6fdf6.png)
11、Data source library table icon modification
![image](https://user-images.githubusercontent.com/57786627/186916274-8c2c9d8e-00ca-4104-b071-cca0d03c69fe.png)

### Use case

no

### solutions

no

### Anything else

no

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by starchouzz** [comment]
The current requirements have been completed
