### ISSUE TITLE
[Feature] [Exchangis1.1.1]Field Mapping Rule Management

### ISSUE THREAD

**Issue by FinalTarget** [WeBankFinTech/Exchangis#377]
### Search before asking

- [X] I had searched in the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar feature requirement.

### Problem Description

At present, the rules for loading field mapping information are written in the form of hard coding. With the supplement and improvement of data source types and engines, the rules involved become more and more complex, and it is very cumbersome to maintain only through the code. Therefore, 1.0 does not completely restrict the field mapping configuration on the interface. It is completely left to the user to identify the configuration right and wrong, causing some confusion in use and testing.

### Description

1. Store the configuration attributes related to field mapping in the background data table. Here we reuse exchangis_ job_ param_ Config table, we can insert a config for each type of data source under different engines and in different derivative directions_ The key is Compared with other configuration records, the mapping task configuration record is used for interface rendering. It is only used to store mapping rules, which are stored in the source field in the form of json.
2. For one For the mapping record, its rules include: the fieldAddEnable field can be added, the fieldEditEnable field can be edited, the fieldDeleteEnable field can be deleted, the fieldTransformEnable field can be converted, and the fieldMatchStrategyName field matching policy (the default is ALL_MATCH_IGNORE_CASE, ignoring full case matching).
According to the defined mapping rules, we load the mapping fields according to the rules, including field matching, and finally return them to the front-end rendering.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by jefftlin** [comment]
The latest version of exchangis is 1.1.2, the latest dss version is 1.1.2, and the latest linkis version is 1.4.0
