### ISSUE TITLE
[Bug] There is a wrong url in the md document, which causes github to fail to compile

### ISSUE THREAD

**Issue by binbinCheng** [WeBankFinTech/Exchangis#380]
**There is a wrong url in the md document, which causes github to fail to compile**

**Example**

![image](https://user-images.githubusercontent.com/106590848/197736402-422a079b-5824-4fdd-b819-51f00d176df0.png)

### Reproduction script

https://linkis.apache.org/zh-CN/docs/latest/deployment/quick_deploy

**Comment by FinalTarget** [comment]
LGTM
