### ISSUE TITLE
[Bug] dss登录exchangis显示未登录

### ISSUE THREAD

**Issue by Yiutto** [WeBankFinTech/Exchangis#390]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar issues.

### Exchangis Component

exchangis-web

### What happened + What you expected to happen

![image](https://user-images.githubusercontent.com/12077317/206948953-c60b2567-bb9c-4f86-8223-e7cfd432d665.png)

exchangis1.0.0
dss1.1.1
linkis 1.2.0

### Relevent platform

exchangis1.0.0
dss1.1.1
linkis 1.2.0

### Reproduction script

You are not logged in

### Anything else

You are not logged in

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by Yiutto** [comment]
https://github.com/WeBankFinTech/DataSphereStudio/issues/933

确实是之前数据库里写了ip，访问用了域名，导致cook ie拿不到问题，后来改ip就没问题了

**Comment by homilais** [comment]
响应数据提示未登入
`
{"method":"/api/rest_j/v1/dss/exchangis/main/projects","status":-1,"message":"You are not logged in, please login first!(您尚未登录，请先登录!)","data":{}}
`
访问的ip已经与dss_appconn_instance中配置的一致，请求中已经添加了cookie
`
Cookie: workspaceId=224; workspaceName=bdapWorkspace; linkis_user_session_ticket_id_v1=M7UZXQP9Ld10ZF3+e15afkDSc4/GFINY2HLiVea4FcQ=
`
