### ISSUE TITLE
[Bug] 安装直通车内容点击跳转后返回404

### ISSUE THREAD

**Issue by xuxyangyang** [WeBankFinTech/Exchangis#398]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar issues.

### Exchangis Component

exchangis-project

### What happened + What you expected to happen

点击红框内容跳转后返回404
![image](https://github.com/WeBankFinTech/Exchangis/assets/54273963/7618cd1e-ddc2-4478-85ae-eef611fa54dd)

### Relevent platform

dev-1.1.2
docs/zh_CN/ch1/exchangis_deploy_cn.md

### Reproduction script

点击红框内容跳转后返回404
![image](https://github.com/WeBankFinTech/Exchangis/assets/54273963/7618cd1e-ddc2-4478-85ae-eef611fa54dd)

### Anything else

无

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by jefftlin** [comment]
The document link issue has been fixed and can be found in the docs directory in the latest version 1.1.2！
