### ISSUE TITLE
[Bug] 大部分超链接跳转返回404

### ISSUE THREAD

**Issue by xuxyangyang** [WeBankFinTech/Exchangis#399]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar issues.

### Exchangis Component

exchangis-dao

### What happened + What you expected to happen

1、[数据源功能使用](https://linkis.apache.org/zh-CN/docs/1.1.0/deployment/start_metadatasource)
![image](https://github.com/WeBankFinTech/Exchangis/assets/54273963/81749ab7-a612-4509-a243-0f97fcaa8c41)

2、[在Linkis中设置并认证hive数据源](https://linkis.apache.org/zh-CN/docs/1.1.1/deployment/start_metadatasource)
![image](https://github.com/WeBankFinTech/Exchangis/assets/54273963/f5f75486-60be-495e-baad-880d82cd3c5c)

3、[Linkis Sqoop 引擎插件安装文档](https://linkis.staged.apache.org/zh-CN/docs/1.1.2/engine_usage/sqoop)
![image](https://github.com/WeBankFinTech/Exchangis/assets/54273963/14f0fe97-9b2e-4c58-af63-38f3c1b4eb66)

### Relevent platform

Exchangis/docs/zh_CN/ch1/exchangis_deploy_cn.md

[Exchangis](https://github.com/WeDataSphere/Exchangis/tree/master)/[docs](https://github.com/WeDataSphere/Exchangis/tree/master/docs)/[zh_CN](https://github.com/WeDataSphere/Exchangis/tree/master/docs/zh_CN)/[ch1](https://github.com/WeDataSphere/Exchangis/tree/master/docs/zh_CN/ch1)
/exchangis_deploy_cn.md

### Reproduction script

1

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

**Comment by jefftlin** [comment]
The document link issue has been fixed and can be found in the docs directory in the latest version 1.1.2！
