### ISSUE TITLE
[Bug] 项目下无任务，不能删除

### ISSUE THREAD

**Issue by xuxyangyang** [WeBankFinTech/Exchangis#400]
### Search before asking

- [X] I searched the [issues](https://github.com/WeBankFinTech/Exchangis/issues) and found no similar issues.

### Exchangis Component

exchangis-project

### What happened + What you expected to happen

项目下无任务，不能删除
http://119.29.217.77:9090/#/projectManage
![企业微信截图_16896740768670](https://github.com/WeBankFinTech/Exchangis/assets/54273963/26e346d1-6af5-4c1e-bd59-6cf2672fff26)
![企业微信截图_16896740842930](https://github.com/WeBankFinTech/Exchangis/assets/54273963/7af8ec41-3c7e-48e5-9010-3f4037b0caeb)
![企业微信截图_16896741024142](https://github.com/WeBankFinTech/Exchangis/assets/54273963/c3fa5ade-a623-4cf3-88fc-3b55257f854e)

### Relevent platform

exchangis1.1.2
exchangis-project
http://119.29.217.77:9090/#/projectManage

### Reproduction script

1

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jefftlin** [comment]
It had been resolved by pr #408
