### ISSUE TITLE
when does exchangis surpport kafka datasource?

### ISSUE THREAD

**Issue by geosmart** [WeBankFinTech/Exchangis#43]

**Comment by Davidhua1996** [comment]
It may involves the stream data transmission. Our prefer option is to change the definition of DataX and make it support our stream data command. We will  release that in 0.6.0.

**Comment by jefftlin** [comment]
The current typesetting is not supported. The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
