### ISSUE TITLE
The new DATAX task cannot list the library names in the ORACLE data source

### ISSUE THREAD

**Issue by snycc15** [WeBankFinTech/Exchangis#46]
Schema/USER in the library cannot be listed, only the service name or instance name in the template creation stage can be listed, and it cannot be named by "library name" here. To be precise, it should be represented by user or Schema.
不能列出库中的Schema/USER，仅仅列出模板创建阶段的服务名或实例名，并且这里不能用“库名”来命名。准确来说应该使用用户或Schema来表示。

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1 and support using serviceName to connect to Oracle.. You can pay attention to it.
