### ISSUE TITLE
When will Exchange IS be integrated into DSS?

### ISSUE THREAD

**Issue by smallkk86** [WeBankFinTech/Exchangis#55]
Want to know about the community's plan to integrate Exchange IS into DSS?Want to know about the community's plan to integrate Exchange IS into DSS?

想了解社区将Exchangis集成到DSS的计划？

**Comment by Davidhua1996** [comment]
1.0 version, now in designing stage.

**Comment by jefftlin** [comment]
Exchangis already integrated into dss. The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
