### ISSUE TITLE
Mysql can't synchronize to es data.

### ISSUE THREAD

**Issue by jackMk** [WeBankFinTech/Exchangis#63]
Mysql can't synchronize to es data.
mysql同步到es数据进不去

**Comment by Davidhua1996** [comment]
can print the log stack information

**Comment by jackMk** [comment]
没有任何问题，就是无法同步，说是后置处理器问题，这个又无法取消

**Comment by jackMk** [comment]
在哪里修改后置处理器选项

**Comment by jefftlin** [comment]
This problem had been solved! The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
