### ISSUE TITLE
> @jkl0898 Excuse me, how to bind the IP? I also encountered this problem.Excuse me, how to bind the IP? I also encountered this problem.

### ISSUE THREAD

**Issue by fs3085** [WeBankFinTech/Exchangis#67]
> @jkl0898 请问如何绑定的IP？我也遇到了此问题

Hello. To check the IP configuration related to the network in your environment, you can check its source logic, the part about IP binding.
You can also debug errors by remote debugging.
你好。需要检查你的环境中网路相关的IP 配置， 你可查询其源码逻辑，关于IP绑定的部分。
也可以通过远程调试的方式调试错误。

_Originally posted by @jkl0898 in https://github.com/WeBankFinTech/Exchangis/issues/12#issuecomment-749307446_

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1. You can pay attention to it.
