### ISSUE TITLE
前端未开源，是不是就不能自行扩展datax接入类型。

### ISSUE THREAD

**Issue by weipengffk** [WeBankFinTech/Exchangis#7]
启动exchangis后，发现不支持 sqlserver,mongodb 等数据库.
初步查看源码，前端未开源。

如果我想新增数据库类型，目前该怎么处理

**Comment by Davidhua1996** [comment]
Data source module in Exchangis will be Integrated into Linkis on the next release version，it will be possible that extending data source type by appeding record in database. But at present, I’m afraid that you can only use the data source types supported by the interface.

**Comment by weipengffk** [comment]
好，期待
