### ISSUE TITLE
Task execution failed, and the error log cannot be seen.

### ISSUE THREAD

**Issue by gmdqtd** [WeBankFinTech/Exchangis#72]
When data is exchanged from MYSQL to MYSQL, only No Logs are available can be seen in the logs of the execution list of task jobs.
从MYSQL交换数据到MYSQL，在任务作业的执行列表的日志里只看到No Logs are available

**Comment by jefftlin** [comment]
This has been solved. The latest version is exchangis1.1.1. You can pay attention to it.
