### ISSUE TITLE
hi, thanks your great project. and how can I extend the databases like hbase ?

### ISSUE THREAD

**Issue by fuxiaofengfu** [WeBankFinTech/Exchangis#74]
hi, thanks your great project. and how can I extend the databases like hbase ?
how can I add hbase datasource or data target ? does this project support extend by myself ? thanks.

**Comment by BohanZhang0222** [comment]
新增数据源似乎比较麻烦，需要写一套逻辑。包括service里的controller，用来解析前端参数。然后需要增加template用来生成标准格式的dataX.json，继承AbstractJobDataConfHandler实现基于template的json构建，然后还要在engine中添加dataX的reader/writer.....以及.....我也不知道还有没有。

个人观点，不见得准确。

**Comment by jefftlin** [comment]
We don't support the current version of. Are you interested in contributing this feature?
