### ISSUE TITLE
When mysql is selected as the data source for task configuration and oracle is selected as the target source, the field mapping is not displayed.

### ISSUE THREAD

**Issue by ITlaishoujian** [WeBankFinTech/Exchangis#76]
![image](https://user-images.githubusercontent.com/53336342/117285868-15923780-ae9b-11eb-94b7-25324c98819c.png)
![image](https://user-images.githubusercontent.com/53336342/117285963-3490c980-ae9b-11eb-9350-dcc37c2fb103.png)

**Comment by ITlaishoujian** [comment]
![image](https://user-images.githubusercontent.com/53336342/117417493-0075e100-af4d-11eb-8109-b03fd3ea1d32.png)

在sources\web-design\src\components\jobAddWrap.fes第296行加上”|| this.FesFesx.FirstCurrentDataSourceType === SOURCETYPE.MYSQL”

**Comment by jefftlin** [comment]
This has been solved. The latest version is exchangis1.1.1. You can pay attention to it.
