### ISSUE TITLE
Why are task jobs displayed in the queue, but data synchronization is actually impossible?

### ISSUE THREAD

**Issue by sunloktom** [WeBankFinTech/Exchangis#79]
![image](https://user-images.githubusercontent.com/85332711/120753305-8cbff780-c53d-11eb-913e-e6af51ddaa94.png)

**Comment by rilweic** [comment]
他们这项目全是bug啊

**Comment by M970203** [comment]
你就没有真正跑起来，排队中一直在死循环，执行节点也没有，当然没有数据同步

**Comment by zhanghaicheng1** [comment]
根据指定ip获取网卡名称，脚本如下：
1、比如你需要绑定的executor的ip是10.0.0.14
2、获取网卡名称如下：
```
#!/bin/bash
ip="10.0.0.14"
interfaces=(`ip l | awk -F":"  '/^[^ ]/{print $2}'| awk '{print $1}'`)
for interface in ${interfaces[*]};do
     rs=`ip a show $interface| grep $ip`
     if [ -n "$rs"   ];then
         echo $interface                                                                                                                                                   
         break
     fi
done
```
3、将获取的网卡名字，比如第二步输出的结果是“em1”
4、将第3步骤的结果配置到`/wedatasphere-exchangis-0.5.0.RELEASE/modules/exchangis-executor/conf/bootstrap.yml`的

network:
    interface:
      name: "em1"
5、重启exchangis-executor、以及exchangis-service服务

./bin/start.sh -m exchangis-executor
./bin/start.sh -m exchangis-service
6、大功告成，附上一张测试成功的截图（hive同步mysql，一条数据）
<img width="1958" alt="image" src="https://user-images.githubusercontent.com/46189785/175271266-69a22d22-3822-44fc-b6ef-a14e11f4285c.png">

**Comment by M970203** [comment]
Thank you！！！！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年06月23日 17:51 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [WeBankFinTech/Exchangis] Why are task jobs displayed in the queue, but data synchronization is actually impossible? (#79) |

根据指定ip获取网卡名称，脚本如下：
1、比如你需要绑定的executor的ip是10.0.0.14
2、获取网卡名称如下：

#!/bin/bash

ip="10.0.0.14"

interfaces=(`ip l | awk -F":"  '/^[^ ]/{print $2}'| awk '{print $1}'`)

for interface in ${interfaces[*]};do

     rs=`ip a show $interface| grep $ip`

     if [ -n "$rs"   ];then

         echo $interface                                                                                                                                                   

         break

     fi

done



3、将获取的网卡名字，比如第二步输出的结果是“em1”
4、将第3步骤的结果配置到/wedatasphere-exchangis-0.5.0.RELEASE/modules/exchangis-executor/conf/bootstrap.yml的

network:
interface:
name: "em1"
5、重启exchangis-executor、以及exchangis-service服务

./bin/start.sh -m exchangis-executor
./bin/start.sh -m exchangis-service
6、大功告成，附上一张测试成功的截图（hive同步mysql，一条数据）

**Comment by jefftlin** [comment]
This has been solved. The latest version is exchangis1.1.1. You can pay attention to it.
