### ISSUE TITLE
Can exchangis support oracle?

### ISSUE THREAD

**Issue by majiajue** [WeBankFinTech/Exchangis#8]
Can exchangis support oracle?
可以支持oracle嘛？

**Comment by Davidhua1996** [comment]
The current version does not support, we put the more data source types in next version.

**Comment by majiajue** [comment]
> The current version does not support, we put the more data source types in next version.

tks,Looking forward to the next version

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
