### ISSUE TITLE
The task is configured with nodes. After executing the task, an error is reported, and the execution node cannot be found.

### ISSUE THREAD

**Issue by sunloktom** [WeBankFinTech/Exchangis#80]
1.
![image](https://user-images.githubusercontent.com/85332711/120768353-9e5dcb00-c54e-11eb-85c2-3975e3d06df4.png)
2.
![image](https://user-images.githubusercontent.com/85332711/120768668-fbf21780-c54e-11eb-8b5d-f1df01322537.png)
3.
![image](https://user-images.githubusercontent.com/85332711/120768735-0c09f700-c54f-11eb-8e9d-8e2c17659fd1.png)
4.error message
报错信息
com.webank.wedatasphere.exchangis.route.exception.NoAvailableServerException: No available candidate servers
	at com.webank.wedatasphere.exchangis.route.MachineLoadRule.choose(MachineLoadRule.java:108)
	at com.webank.wedatasphere.exchangis.route.MachineLoadRule.choose(MachineLoadRule.java:65)

**Comment by sunice0813** [comment]
这个是因为在exchangis-executor里面缺少配置，导致程序getHost的时候两边不匹配。
<img width="354" alt="image" src="https://user-images.githubusercontent.com/26400435/122388507-86506780-cfa2-11eb-8910-4714a4159846.png">
1.你先看你的这个表里面的address的值是什么
2在你的服务器上用ip r 查看ip
3.接着在exchangis-executor 的conf/application.yml 添加如下配置
executor:
  network:
    interface:
      name: eth0

我这边用的是eth0，至于你的实际情况要看你步骤2的情况填相应的值。一般来说应该就是eth0

**Comment by iwasjoker** [comment]
借大佬issue。
第三点exechangis-executor应该是修改conf/bootstrap.yml文件，将文件底部的name "" 修改为 name "eth0"(读取到的ip应该和eureka注册的ip一致)，修改完重启executor模块。感谢大佬的issue给了提示

**Comment by zhanghaicheng1** [comment]
根据指定ip获取网卡名称，脚本如下：
eg:
1、比如你需要绑定的executor的ip是10.0.0.14
2、获取网卡名称如下：
```
#!/bin/bash
ip="10.0.0.14"
interfaces=(`ip l | awk -F":"  '/^[^ ]/{print $2}'| awk '{print $1}'`)
for interface in ${interfaces[*]};do
     rs=`ip a show $interface| grep $ip`
     if [ -n "$rs"   ];then
         echo $interface                                                                                                                                                   
         break
     fi
done
```
3、将获取的网卡名字，比如第二步输出的结果是“em1”
4、将第3步骤的结果配置到`/wedatasphere-exchangis-0.5.0.RELEASE/modules/exchangis-executor/conf/bootstrap.yml`的
```
network:
    interface:
      name: "em1"
```
5、重启exchangis-executor、以及exchangis-service服务
```
./bin/start.sh -m exchangis-executor
./bin/start.sh -m exchangis-service
```
6、大功告成，附上一张测试成功的截图（hive同步mysql，一条数据）
<img width="1958" alt="image" src="https://user-images.githubusercontent.com/46189785/175269262-33c4033c-1520-479f-9b8e-6ad0e58c2617.png">

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1 and had supported MySQL、Hive、MongoDB、ElasticSearch and Oracle. You can pay attention to it.
