### ISSUE TITLE
Error message “unable to find instance for exchangis-service”

### ISSUE THREAD

**Issue by HappyGoIT** [WeBankFinTech/Exchangis#93]
127.0.0.1:9503 can be opened, but the prompt "unable to find instance for exchange is-service" appears, and this prompt appears for all menu functions.
可打开127.0.0.1:9503，但是提示unable to find instance for exchangis-service，所有菜单功能一点也出现这个提示。

**Comment by jefftlin** [comment]
The latest version is exchangis1.1.1 and had fixed this problem. You can pay attention to it.
